# Generated by Django 3.0 on 2020-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0003_auto_20200331_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='media',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
    ]
