# Generated by Django 3.0 on 2020-03-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0004_auto_20200331_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_crawler.Artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_crawler.Band'),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
