# Generated by Django 3.0 on 2020-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0005_auto_20200331_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=25)),
                ('current_message', models.CharField(default='Initializing...', max_length=255)),
                ('succeded', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='music',
            name='band',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
