# Generated by Django 3.0 on 2020-05-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0006_auto_20200514_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlogs',
            name='succeded',
        ),
        migrations.AddField(
            model_name='downloadlogs',
            name='errored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadlogs',
            name='succeeded',
            field=models.BooleanField(default=False),
        ),
    ]
