# Generated by Django 3.0 on 2020-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0007_auto_20200518_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadLogs',
        ),
    ]
