# Generated by Django 3.0 on 2020-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0009_downloadcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('yt_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='yt_id',
            field=models.CharField(default='youtube', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadcount',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
