# Generated by Django 3.0 on 2020-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0010_auto_20200519_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmusic',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
