# Generated by Django 3.0 on 2020-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0011_cachedmusic_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedmusic',
            name='yt_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
