# Generated by Django 3.0 on 2020-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0012_auto_20200521_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmusic',
            name='is_downloading',
            field=models.BooleanField(default=False),
        ),
    ]
