# Generated by Django 3.0 on 2020-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0013_cachedmusic_is_downloading'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
