# Generated by Django 3.0 on 2020-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0014_music_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='media',
            field=models.FileField(null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='yt_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
