# Generated by Django 3.0 on 2020-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_crawler', '0015_auto_20200524_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmusic',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
